### ISSUE TITLE
Fix translation!

### ISSUE THREAD

**Issue by evgfilim1** [metroyanno/BTCWalletHelperBot#1]

**Comment by metroyanno** [comment]
Fix? Or correct translation?

I not strange in English, write me pull request please

**Comment by OctoNezd** [comment]
@metroyanno Я НЕ СТРАННЫЙ В АНГЛИЙСКОМ

**Comment by metroyanno** [comment]
@OctoNezd Ха-ха

**Comment by OctoNezd** [comment]
смешно же
